# --------------------- #
#    Generation File    #
# --------------------- #

pkgs = [
  "lld",
  "gvfs",
  "udisks2",
  "parted",
  "gparted",
  "git",
  "flatpak",
  "rustup",
  "rust-analyzer",
  "python",
  "python-pip",
  "helix",
  "bat",
  "exa",
  "brave-bin",
  "thunar",
  "noto-fonts-emoji",
  "libnotify",
  "notification-daemon",
  "hyprland",
  "cliphist",
  "waybar",
  "alacritty",
  "rofi-lbonn-wayland",
  "swww",
  "swaync",
  "networkmanager",
  "network-manager-applet",
  "bluez",
  "bluez-utils",
  "blueman",
  "papirus-icon-theme",
  "noto-fonts-emoji",
  "lxsession",
  "grimblast",
  "brightnessctl",
  "light",
  "nwg-look-bin",
  "yad",
  "sox",
  "mint-themes",
  "xcursor-simp1e-gruvbox-light",
  "gtklock",
  "eww-wayland",
  "xdg-desktop-portal-hyprland",
  "sddm-git",
  "cmatrix",
  "clido",
  "flattools",
  "dmenu-to-rofi",
  "cermic",
  "grape",
  "pytool",
  "rupell",
  "tmux",
  "browsh-bin",
  "fastfetch",
  "chafa",
  "starship",
  "namcap",
  "cava",
]

flatpaks = [
  "flatseal",
  "whatip",
  "supertuxkart",
]
