# --------------------- #
#    Generation File    #
# --------------------- #

# !pkgs.start
pkgs = [
  "lld",
  "llvm",
  "gvfs",
  "udisks2",
  "parted",
  "gparted",
  "git",
  "flatpak",
  "rustup",
  "rust-analyzer",
  "rust-src",
  "python",
  "python-pip",
  "helix",
  "bat",
  "exa",
  "brave-bin",
  "thunar",
  "noto-fonts-emoji",
  "libnotify",
  "notification-daemon",
  "hyprland",
  "cliphist",
  "waybar",
  "alacritty",
  "rofi-lbonn-wayland-git",
  "swww",
  "swaync",
  "networkmanager",
  "network-manager-applet",
  "bluez",
  "bluez-utils",
  "blueman",
  "papirus-icon-theme",
  "noto-fonts-emoji",
  "lxsession",
  "grimblast",
  "brightnessctl",
  "light",
  "nwg-look-bin",
  "yad",
  "sox",
  "mint-themes",
  "xcursor-simp1e-gruvbox-light",
  "gtklock",
  "eww-wayland",
  "xdg-desktop-portal",
  "xdg-desktop-portal-hyprland",
  "qt5-wayland",
  "qt5ct",
  "obs-studio",
  "pipewire",
  "sddm-git",
  "neo-matrix-git",
  "clido",
  "flattools",
  "dmenu-to-rofi",
  "cermic",
  "grape",
  "pytool",
  "rupell",
  "tmux",
  "browsh-bin",
  "fastfetch",
  "chafa",
  "starship",
  "namcap",
  "cava",
  "gimp",
  "nushell",
  "gthumb",
  "notepadqq",
]
# !pkgs.end

# !flatpak.start
flatpaks = [
  "flatseal",
  "whatip",
  "supertuxkart",
]
# !flatpak.end
