# --------------------- #
#    Generation File    #
# --------------------- #

# !imports.start
imports = [
  "core_packages",
  "programming_languages",
  "hyprland",
  "proprietary",
]
# !imports.end

# !pkgs.start
pkgs = [
  "flatpak",
  "gparted",
  "helix",
  "bat",
  "eza",
  "brave-bin",
  "thunar",
  "noto-fonts-emoji",
  "grimblast-git",
  "noto-fonts-emoji",
  "obs-studio",
  "qt5ct",
  "pipewire",
  "sddm-git",
  "neo-matrix-git",
  "clido",
  "flattools",
  "dmenu-to-rofi",
  "cermic",
  "grape",
  "pytool",
  "rupell",
  "zellij",
  "fastfetch",
  "cutefetch",
  "chafa",
  "starship",
  "namcap",
  "cava",
  "gimp",
  "nushell",
  "gthumb",
  "lite-xl-bin",
  "mpv",
  "gnome-calculator",
  "binum",
  "coin-flipper",
  "appimagelauncher",
  "ncdu",
  "libreoffice-fresh",
  "wine",
  "transmission-gtk",
  "htop",
  "tty-clock-git",
  "asciiquarium",
  "lolcat",
  "catlol",
  "lavat-git",
  "moon-buggy",
  "arp-scan",
  "tigervnc",
  "dir-watcher",
  "gnome-disk-utility",
]
# !pkgs.end

# !flatpak.start
flatpaks = [
  "flatseal",
  "whatip",
  "supertuxkart",
  "signal",
]
# !flatpak.end

# !crates.start
crates = [
  "bacon",
  "cargo-info",
  "cargo-update",
  "cargo-expand",
  "cargo-show-asm",
  "irust",
  "speedtest-rs",
  "wiki-tui",
  "mprocs",
]
# !crates.end
