# --------------------- #
#    Generation File    #
# --------------------- #

# !imports.start
imports = [
  "hyprland",
]
# !imports.end

# !pkgs.start
pkgs = [
  "linux-zen",
  "linux-zen-headers",
  "lld",
  "llvm",
  "gvfs",
  "udisks2",
  "parted",
  "gparted",
  "git",
  "flatpak",
  "rustup",
  "rust-analyzer",
  "rust-src",
  "python",
  "python-pip",
  "python-pipx",
  "helix",
  "bat",
  "eza",
  "brave-bin",
  "thunar",
  "noto-fonts-emoji",
  "grimblast-git",
  "noto-fonts-emoji",
  "obs-studio",
  "qt5ct",
  "pipewire",
  "sddm-git",
  "neo-matrix-git",
  "clido",
  "flattools",
  "dmenu-to-rofi",
  "cermic",
  "grape",
  "pytool",
  "rupell",
  "zellij",
  "fastfetch",
  "chafa",
  "starship",
  "namcap",
  "cava",
  "gimp",
  "nushell",
  "gthumb",
  "lite-xl-bin",
  "mpv",
  "gnome-calculator",
  "binum",
  "coin-flipper",
  "appimagelauncher",
  "ncdu",
  "libreoffice-fresh",
  "wine",
  "transmission-gtk",
  "htop",
]
# !pkgs.end

# !flatpak.start
flatpaks = [
  "flatseal",
  "whatip",
  "supertuxkart",
  "signal",
]
# !flatpak.end

# !crates.start
crates = [
  "bacon",
  "cargo-info",
  "cargo-update",
  "cargo-expand",
  "cargo-show-asm",
  "irust",
  "speedtest-rs",
]
# !crates.end
