add = "sudo emerge -vaNUg #:? --jobs $(($(nproc) / 2)) --autounmask --autounmask-write"
remove = "sudo emerge -cav #:?"

plural_name = "initial packages"

hook_name = "initial_packages"

[config]
many_args = true
