add = "time sudo emerge -vaNUg #:?"
remove = "time sudo emerge -cav #:?"
sync = "~/.config/rebos/scripts/portage_sync.sh"
upgrade = "~/.config/rebos/scripts/portage_upgrade.sh"

plural_name = "system packages"

hook_name = "system_packages"

[config]
many_args = true
