add = "time sudo emerge -vaNUg #:? --jobs $(($(nproc) / 2)) --autounmask --autounmask-write"
remove = "time sudo emerge -cav #:?"
sync = "time sudo emerge --sync -a"
upgrade = "time sudo emerge -avuDUg @world"

plural_name = "system packages"

hook_name = "system_packages"

[config]
many_args = true
