add = "sudo emerge -vaNUg #:? --autounmask --autounmask-write"
remove = "sudo emerge -cav #:?"
sync = "sudo emerge --sync -a"
upgrade = "sudo emerge -avuDUg @world"

plural_name = "system packages"

[config]
many_args = true
