add = "sudo emerge -aNUg #:? --autounmask --autounmask-write"
remove = "sudo emerge -cav #:?"
sync = "sudo emerge --sync"
upgrade = "sudo emerge -vuDNUg @world"

plural_name = "system packages"

[config]
many_args = true
