# --------------------- #
#    Generation File    #
# --------------------- #

imports = [
    "intensive",
    "intensive_proprietary",
    "gpu_drivers/amd",
    "laptop",
]

[managers.system]
items = [
]

[managers.flatpak]
items = [
    "net.ankiweb.Anki",
]
