imports = [
  "kde_full",
  "astro",
]

[managers.system]
items = [
  "sys-apps/openrazer",
  "sys-apps/polychromatic",
  "sys-apps/amdgpu_top",
  "www-client/librewolf",
  "www-client/ungoogled-chromium",
  "dev-lang/rust",
  "app-office/libreoffice",
  "net-misc/rustdesk",
  "dev-util/rocm-smi",
  "dev-util/rocminfo",
  "dev-libs/rocm-opencl-runtime",
  "dev-libs/rocm-comgr",
  "sci-ml/ollama",
  "llvm-runtimes/openmp",
]

[managers.flatpak]
items = [
]

[managers.cargo]
items = [
]

[managers.serv_user_startup]
items = [
    "openrazer-daemon",
]
