imports = [
  "kde_full",
]

[managers.system]
items = [
  "x11-drivers/nvidia-drivers",
  "sys-apps/openrazer",
  "sys-apps/polychromatic",
  "app-containers/nvidia-container-toolkit",
]

[managers.flatpak]
items = [
]

[managers.cargo]
items = [
]

[managers.serv_user_startup]
items = [
    "openrazer-daemon",
]
