imports = [
  "kde_full",
  "astro",
  "hack",
]

[managers.system]
items = [
  "sys-apps/openrazer",
  "sys-apps/polychromatic",
  "sys-apps/amdgpu_top",
  "www-client/librewolf",
  "www-client/brave-browser",
  "dev-lang/rust",
  "app-office/libreoffice",
  "net-misc/rustdesk",
  "dev-libs/roct-thunk-interface",
  "dev-libs/rocr-runtime",
  "dev-libs/rocm-device-libs",
  "dev-libs/rocm-comgr",
  "dev-libs/rocm-opencl-runtime",
  "dev-util/hip",
  "dev-util/hipcc",
  "dev-util/rocminfo",
  "llvm-runtimes/openmp",
  "sci-misc/llama-cpp",
  "sci-ml/huggingface_hub",
]

[managers.flatpak]
items = [
]

[managers.cargo]
items = [
]

[managers.openrc_user]
items = [
    "openrazer-daemon",
]
