# --------------------- #
#    Generation File    #
# --------------------- #

imports = [
    "intensive",
    "intensive_proprietary",
    "gpu_drivers/amd",
]

pkgs = [
    "jitsi-meet-desktop-bin",
]

flatpaks = [
]

crates = [
]
