# --------------------- #
#    Generation File    #
# --------------------- #

pkgs = [
    "xf86-video-amdgpu",
    "vulkan-radeon",
    "lib32-vulkan-radeon",
    "element-desktop",
    "kdenlive",
    "virtualbox",
    "virtualbox-guest-iso",
    "virtualbox-guest-utils",
    "virtualbox-host-dkms",
    "godot",
]

flatpaks = [
    "simple64",
    "blanket",
    "blockbench",
    "codium",
    "blender",
]
