# --------------------- #
#    Generation File    #
# --------------------- #

pkgs = [
    "xf86-video-amdgpu",
    "vulkan-radeon",
    "blender",
    "element-desktop",
    "kdenlive",
    "lmms",
]

flatpaks = [
    "simple64",
    "blanket",
    "blockbench",
    "codium",
]
