# --------------------- #
#    Generation File    #
# --------------------- #

imports = [
    "intensive",
    "intensive_proprietary",
    "gpu_drivers/amd",
]

pkg_managers.system.pkgs = [
    "jitsi-meet-desktop-bin",
]
