# --------------------- #
#    Generation File    #
# --------------------- #

imports = [
    "intensive",
    "intensive_proprietary",
]

pkgs = [
    "xf86-video-amdgpu",
    "vulkan-radeon",
    "lib32-vulkan-radeon",
    "jitsi-meet-desktop-bin",
]

flatpaks = [
]

crates = [
]
