# System

add = "sudo xbps-install #:?"
remove = "sudo xbps-remove #:?"
sync = "sudo xbps-install -S"
upgrade = "sudo xbps-install -Su"

plural_name = "initial packages"

hook_name = "initial_packages"

[config]
many_args = true
