# System

add = "sudo xbps-install #:?"
remove = "sudo xbps-remove #:?"
sync = "sudo xbps-install -S"
upgrade = "sudo xbps-install -Su"

plural_name = "system packages (pre)"

hook_name = "system_packages_pre"

[config]
many_args = true
