imports = [
  "initial_packages",
  "core",
  "shell_completions",
  "noto",
  "portage",
  "gpm",
  "bluetooth",
  "gaming",
  "virtualization",
  "office",
]

[managers.system]
items = [
  "app-misc/fastfetch",
  "sys-block/gparted",
  "app-editors/helix",
  "sys-apps/eza",
  "sys-apps/bat",
  "app-shells/fzf",
  "sys-process/htop",
  "sys-process/btop",
  "app-portage/eix",
  "www-client/links",
  "media-gfx/gimp",
  "games-misc/lolcat",
  "games-misc/cowsay",
  "app-misc/cmatrix",
  "net-analyzer/arp-scan",
  "net-p2p/qbittorrent",
  "dev-python/pipx",
  "dev-util/android-tools",
  "app-misc/sl",
]

[managers.flatpak]
items = [
  "com.github.tchx84.Flatseal",
  "org.raspberrypi.rpi-imager",
  "com.stremio.Stremio",
  "com.rafaelmardojai.Blanket",
  "com.usebottles.bottles",
]

[managers.cargo]
items = [
]
