imports = [
  "initial_packages",
  "core",
  "shell_completions",
  "noto",
  "wayland_apps",
  "rices/hyprland",
]

[managers.system]
items = [
  "app-misc/fastfetch",
  "sys-block/gparted",
  "app-editors/neovim",
  "app-shells/starship",
  "sys-apps/eza",
  "sys-apps/bat",
  "app-misc/zellij",
  "app-shells/fzf",
  "xfce-base/thunar",
  "media-sound/pavucontrol",
  "sys-process/htop",
  "app-portage/eix",
  "www-client/brave-bin",
  "media-video/mpv",
  "media-gfx/gimp",
  "net-irc/senpai",
]

[managers.flatpak]
items = [
  "com.github.tchx84.Flatseal",
  "org.gabmus.whatip",
  "net.supertuxkart.SuperTuxKart",
  "org.supertuxproject.SuperTux",
  "org.raspberrypi.rpi-imager",
  "im.riot.Riot",
]

[managers.cargo]
items = [
  "bacon",
  "cargo-info",
  "cargo-update",
  "cargo-expand",
  "cargo-show-asm",
  "irust",
  "cermic",
  "tuido",
]
