imports = [
  "initial_packages",
  "core",
  "gui_core",
  "shell_completions",
  "noto",
  "wayland_apps",
  "rices/hyprland",
  "qt",
  "appimage_dependencies",
  "portage",
  "gtk_themes",
  "icon_themes",
  "gpm",
  "vr",
  #"bluetooth",
]

[managers.system]
items = [
  "app-misc/fastfetch",
  "sys-block/gparted",
  "app-editors/neovim",
  "app-editors/helix",
  "app-shells/starship",
  "sys-apps/eza",
  "sys-apps/bat",
  "app-misc/zellij",
  "app-shells/fzf",
  "xfce-base/thunar",
  "media-sound/pavucontrol",
  "sys-process/htop",
  "sys-process/btop",
  "app-portage/eix",
  "www-client/brave-bin",
  "www-client/links",
  "media-video/mpv",
  "media-gfx/gimp",
  "net-irc/senpai",
  "app-text/wgetpaste",
  "games-misc/asciiquarium",
  "media-sound/cava",
  "app-misc/tty-clock",
  "games-misc/lolcat",
  "games-misc/sex",
  "games-misc/cowsay",
  "games-action/moon-buggy",
  "sys-fs/ncdu",
  "x11-misc/gammastep",
  "media-gfx/gthumb",
  "games-misc/cbonsai",
  "app-misc/pipes-rs",
  "app-misc/cmatrix",
  "net-analyzer/arp-scan",
  "gnome-extra/gnome-calculator",
  "gui-apps/wlr-randr",
  "app-editors/ghex",
  "dev-python/ipython",
  "net-p2p/transmission",
  "games-puzzle/bastet",
  "games-arcade/ninvaders",
  "games-puzzle/nudoku",
  "net-misc/telnet-bsd",
  "x11-terms/cool-retro-term",
  "sys-devel/qbe",
  "dev-python/pipx",
  "x11-misc/ydotool",
  "dev-util/android-tools",
  "app-misc/sl",
  "app-misc/nwg-look",
  "media-sound/playerctl",
]

[managers.flatpak]
items = [
  "com.github.tchx84.Flatseal",
  "one.ablaze.floorp",
  "org.gabmus.whatip",
  "net.supertuxkart.SuperTuxKart",
  "org.supertuxproject.SuperTux",
  "org.raspberrypi.rpi-imager",
  "im.riot.Riot",
  "org.godotengine.Godot",
  "org.inkscape.Inkscape",
  "com.github.reds.LogisimEvolution",
  "net.ankiweb.Anki",
  "org.kde.kdenlive",
  "com.obsproject.Studio",
  "dev.vencord.Vesktop",
  "org.kde.krita",
  "org.xonotic.Xonotic",
  "com.stremio.Stremio",
  "org.ardour.Ardour",
  "com.rafaelmardojai.Blanket",
  "org.tenacityaudio.Tenacity",
]

[managers.cargo]
items = [
  "bacon",
  "cargo-info",
  "cargo-update",
  "cargo-expand",
  "cargo-show-asm",
  "irust",
  "cermic",
  "tuido",
  "rainfuck-cli",
  "shabi",
  "retch",
  "termova",
  "ttyper",
  "tui48",
  "bong-song",
]
