imports = [
  "initial_packages",
  "core",
  "shell_completions",
  "noto",
  "portage",
  "gpm",
  "bluetooth",
  "gaming",
  "virtualization",
  "office",
]

[managers.system]
items = [
  "app-misc/fastfetch",
  "sys-block/gparted",
  "sys-process/htop",
  "app-portage/eix",
  "media-gfx/gimp",
  "games-misc/lolcat",
  "games-misc/cowsay",
  "app-misc/cmatrix",
  "net-analyzer/arp-scan",
  "net-p2p/qbittorrent",
  "dev-python/uv",
  "dev-util/android-tools",
  "app-misc/sl",
  "sys-apps/ethtool",
  "media-libs/exiftool",
  "app-misc/jq",
  "app-misc/tmux",
]

[managers.flatpak]
items = [
  "com.github.tchx84.Flatseal",
  "org.raspberrypi.rpi-imager",
  "com.stremio.Stremio",
  "com.rafaelmardojai.Blanket",
  "com.usebottles.bottles",
  "com.vysp3r.ProtonPlus",
  "org.ghidra_sre.Ghidra",
  "org.gnome.Firmware",
]

[managers.cargo]
items = [
]
