[managers.system]
items = [
  "rustup",
  "rust",
  "cargo",
]

[managers.rustup_components]
items = [
  "rust-src",
  "rust-std",
  "rust-docs",
  "rust-analyzer",
  "rust-analysis",
  "rustc",
  "cargo",
]
