# --------------------- #
#    Generation File    #
# --------------------- #

imports = [
    "intensive",
    "intensive_proprietary",
    "gpu_drivers/amd",
]

[managers.system]
items = [
    "jitsi-meet-desktop-bin",
]
