# --------------------- #
#    Generation File    #
# --------------------- #

pkgs = [
  "xf86-video-intel",
  "vulkan-intel",
  "intel-media-driver",
  "intel-gmmlib",
  "intel-compute-runtime",
]

flatpaks = [
]
