# --------------------- #
#    Generation File    #
# --------------------- #

# Packages to be installed via the native package manager.
pkgs = [
    # "git",
]

# Packages to be installed via Flatpak.
flatpaks = [
    # "flatseal",
]
