#!/usr/bin/env bash

system_files_path="$HOME/.config/rebos/system_files"

overwrite_file () {
  use_sudo=0

  src="$1"
  dest="$2"

  [[ "$OFSUDO" == 1 ]] && use_sudo=1

  cmd_to_exec="cp"

  [[ "$use_sudo" == 1 ]] && cmd_to_exec="sudo ${cmd_to_exec}"

  exit_status=0

  $cmd_to_exec "$src" "$dest" > /dev/null 2>&1 || exit_status=1

  echo -en "\033[1;93mOVERWRITE\033[0m \033[0;96m${src}\033[0m -> \033[0;95m${dest}\033[0m "

  if [[ "$exit_status" == 0 ]]; then
    echo -e "\033[1;92m(^-^)\033[0m"
  else
    echo -e "\033[1;91m(T~T)\033[0m"
  fi

  return $exit_status
}

add_group_to_user () {
    if groups "$2" | tr ' ' '\n' | grep "$1" > /dev/null 2>&1; then
        echo -e "User \033[0;36m$2\033[0m already has group: '\033[0;96m$1\033[0m' (skipping...)"

        return
    fi

    if sudo usermod -aG "$1" "$2"; then
        echo -e "Successfully added group '\033[0;96m$1\033[0m' to user \033[0;36m$2\033[0m! :D\033[0m"
    else
        echo -e "Failed to add group '\033[0;96m$1\033[0m' to user \033[0;36m$2\033[0m! :(\033[0m"

        exit 1
    fi
}

# User Groups
add_group_to_user audio "${USER}"
add_group_to_user cdrom "${USER}"
add_group_to_user floppy "${USER}"
add_group_to_user portage "${USER}"
add_group_to_user usb "${USER}"
add_group_to_user video "${USER}"
add_group_to_user wheel "${USER}"
add_group_to_user pipewire "${USER}"
add_group_to_user dialout "${USER}"
add_group_to_user android "${USER}"
add_group_to_user plugdev "${USER}"

# Virtualization Stuff (QEMU)
if command -v virt-manager > /dev/null 2>&1; then
    echo "Detected VirtManager... setting up VirtManager stuff..."

    add_group_to_user libvirt "${USER}"
fi

# Virtualization Stuff (QEMU)
if command -v cupsd > /dev/null 2>&1; then
    echo "Detected CUPS... setting up CUPS stuff..."

    add_group_to_user lp "${USER}"
    add_group_to_user lpadmin "${USER}"
fi

## CHECK
#if [[ -f /etc/libvirt/qemu.conf ]]; then
#    OFSUDO=1 overwrite_file "$system_files_path/qemu.conf" "/etc/libvirt/qemu.conf" || exit 1
#fi

if [[ -f /var/cache/ccache/ccache.conf ]]; then
    OFSUDO=1 overwrite_file "$system_files_path/ccache/ccache.conf" "/var/cache/ccache/ccache.conf" || exit 1
fi

# Eselect Stuff
sudo eselect editor set /usr/bin/nano

# ENV Variables (System-Wide)
OFSUDO=1 overwrite_file "$system_files_path/environment" "/etc/environment" || exit 1

# Update Environment
sudo env-update

# For app-backup/grub-btrfs
sudo grub-mkconfig -o /boot/grub/grub.cfg
