# ----------------------------------- #
#    Package Manager Configuration    #
# ----------------------------------- #

install = "paru -S #:?"
remove = "paru -Rns #:?"
sync = "paru -Syy"
upgrade = "paru -Syyu"

# ------------------------------- #
#    Additional configuration.    #
# ------------------------------- #

plural_name = "system packages"

config = { many_pkg_args = true }
