[managers.system]
items = [
  "app-editors/nano",
  "app-editors/vim",
  "dev-vcs/git",
  "net-misc/networkmanager",
  "sys-devel/llvm",
  "sys-devel/llvm-common",
  "sys-devel/clang",
  "sys-devel/clang-common",
  "sys-devel/clang-runtime",
  "sys-devel/lld",
  "sys-devel/gcc",
  "sys-devel/gcc-config",
  "sys-devel/binutils",
  "sys-devel/binutils-config",
  "sys-libs/binutils-libs",
  "sys-block/parted",
  "app-arch/zip",
  "app-arch/unzip",
  "app-arch/tar",
  "app-arch/7zip",
  "sys-apps/coreutils",
  "sys-apps/findutils",
  "sys-devel/binutils",
  "sys-devel/binutils-config",
  "sys-libs/binutils-libs",
  "sys-apps/dbus",
  "sys-auth/polkit",
  "dev-build/make",
  "dev-build/cmake",
  "dev-build/meson",
  "dev-lang/python",
  "net-misc/curl",
  "net-misc/wget",
  "sys-devel/gettext",
  "sys-apps/pciutils",
  "dev-util/tree-sitter-cli",
  "media-libs/glfw",
  "media-libs/glew",
  "media-sound/alsa-utils",
  "media-plugins/alsa-plugins",
  "sys-fs/xfsprogs",
  "sys-fs/e2fsprogs",
  "sys-fs/dosfstools",
  "sys-fs/btrfs-progs",
  "sys-fs/f2fs-tools",
  "sys-fs/ntfs3g",
  "sys-fs/zfs",
  "dev-debug/gdb",
  "sys-auth/rtkit",
  "dev-libs/light",
  "media-sound/sox",
  "dev-util/ccache",
  "app-admin/btrfs-assistant",
  "app-backup/snapper",
  "app-backup/grub-btrfs",
  "app-shells/zsh",
  "app-shells/zsh-autosuggestions",
  "app-shells/zsh-syntax-highlighting",
  "sys-kernel/dkms",
]

[managers.serv_startup]
items = [
  "NetworkManager",
  "dbus",
  "grub-btrfsd",
]
