[managers.system]
items = [
  "app-editors/nano",
  "app-editors/vim",
  "dev-vcs/git",
  "net-misc/networkmanager",
  "sys-devel/llvm",
  "sys-devel/llvm-common",
  "sys-devel/clang",
  "sys-devel/clang-common",
  "sys-devel/clang-runtime",
  "sys-devel/lld",
  "sys-devel/gcc",
  "sys-devel/gcc-config",
  "sys-devel/binutils",
  "sys-devel/binutils-config",
  "sys-libs/binutils-libs",
  "sys-block/parted",
  "app-arch/zip",
  "app-arch/unzip",
  "app-arch/tar",
  "app-arch/7zip",
  "sys-apps/coreutils",
  "sys-apps/findutils",
  "sys-devel/binutils",
  "sys-devel/binutils-config",
  "sys-libs/binutils-libs",
  "sys-apps/dbus",
  "sys-auth/elogind",
  "sys-auth/polkit",
  "dev-build/make",
  "dev-build/cmake",
  "dev-build/meson",
  "dev-lang/python",
  "net-misc/curl",
  "net-misc/wget",
  "sys-devel/gettext",
  "sys-apps/pciutils",
  "dev-util/tree-sitter-cli",
  "media-libs/glfw",
  "media-libs/glew",
  "media-sound/alsa-utils",
]

[managers.openrc]
items = [
  "NetworkManager",
  "dbus",
  "elogind",
]

[managers.openrc_boot]
items = [
]
