[managers.system]
items = [
    "games-util/game-device-udev-rules",
    "games-util/gamemode",
    "gui-wm/gamescope",
]

[managers.flatpak]
items = [
    "net.davidotek.pupgui2",
    "com.valvesoftware.Steam",
]