[managers.system]
items = [
    "kde-plasma/plasma-meta",
    "kde-apps/kdeaccessibility-meta",
    "kde-apps/kdeadmin-meta",
    "kde-apps/kdegraphics-meta",
    "kde-apps/kdemultimedia-meta",
    "kde-apps/kdenetwork-meta",
    "kde-apps/kdeutils-meta",
    "kde-apps/dolphin",
    "kde-apps/kdialog",
    "kde-apps/keditbookmarks",
    "kde-apps/kfind",
    "kde-apps/khelpcenter",
    "kde-apps/konsole",
    "kde-plasma/plasma-login-sessions",
    "kde-plasma/plasma-nm",
    "kde-plasma/bluedevil",
    "x11-misc/sddm",
]

[managers.serv_startup]
items = [
    "sddm",
]

[managers.serv_user_startup]
items = [
    "pipewire-pulse",
    "wireplumber",
    "pipewire",
]