[managers.system]
items = [
    "kde-plasma/plasma-meta",
    "kde-apps/kde-apps-meta",
    "kde-plasma/plasma-login-sessions",
    "kde-plasma/plasma-nm",
    "kde-plasma/bluedevil",
    "x11-misc/sddm",
]

[managers.serv_startup]
items = [
    "sddm",
    "pipewire-pulse",
    "wireplumber",
    "pipewire",
]