[managers.system]
items = [
  "net-print/cups-meta",
  "app-admin/bitwarden-desktop-bin",
  "net-im/discord",
  "net-print/hplip",
  "app-editors/vscode",
  "net-ftp/filezilla",
  "net-misc/remmina",
  "media-gfx/sane-airscan",
  "media-video/vlc",
  "net-misc/nextcloud-client",
  "dev-libs/opensc",
#  "gui-apps/packettracer",
  "sys-apps/pcsc-tools",
  "media-sound/picard",
  "media-sound/puddletag",
  "media-gfx/rawtherapee",
  "net-im/signal-desktop-bin",
  "net-p2p/syncthing",
  "net-analyzer/wireshark",
  "dev-libs/opensc",
  "sys-boot/ventoy-bin",
  "app-admin/awscli",
]

[managers.flatpak]
items = [
    "org.upscayl.Upscayl",
    "com.borgbase.Vorta",
    "com.openterface.openterfaceQT",
]

[managers.serv_startup]
items = [
  "cups"
]

[managers.serv_user_startup]
items = [
    "syncthing",
]
