[managers.system]
items = [
    "app-emulation/virt-manager",
    "app-emulation/libvirt",
    "app-containers/docker",
    "app-containers/docker-compose",
    "app-admin/helm",
    "sys-cluster/kubectl",
    "app-containers/distrobox",
    "app-admin/ansible-core",
    "dev-python/pywinrm",
]

[managers.flatpak]
items = [
    "io.github.dvlv.boxbuddyrs",
]

[managers.openrc]
items = [
    "libvirtd",
    "docker",
]
