[managers.system]
items = [
    "app-emulation/virt-manager",
    "app-emulation/libvirt",
    "app-containers/docker",
    "app-containers/docker-compose",
    "app-containers/nvidia-container-toolkit",
    "app-admin/helm",
    "sys-cluster/kubectl",
]

[managers.serv_startup]
items = [
    "libvirtd",
]
