[managers.system]
items = [
  "app-admin/bitwarden-desktop-bin",
  "app-admin/bitwarden-cli-bin",
]

[managers.flatpak]
items = [
    "com.synology.SynologyAssistant",
    "com.mikrotik.WinBox",
    "com.anydesk.Anydesk",
]

[managers.openrc]
items = [
]
