imports = [
    "virt-manager",
]

[managers.system]
items = [
    "element-desktop",
    "mission-center",
    "waydroid",
    "lutris",
]

[managers.flatpak]
items = [
    "simple64",
    "blanket",
    "blockbench",
    "codium",
    "org.polymc.PolyMC",
    "org.kde.kdenlive",
    "org.blender.Blender",
]
