imports = [
    "virt-manager",
    "virtualbox",
    "vr",
]

[managers.system]
items = [
    "element-desktop",
    "mission-center",
    "waydroid",
    "lutris",
]

[managers.flatpak]
items = [
    "io.github.simple64.simple64",
    "com.rafaelmardojai.Blanket",
    "net.blockbench.Blockbench",
    "com.vscodium.codium",
    "org.polymc.PolyMC",
    "org.blender.Blender",
]
