imports = [
    "themes",
]

[managers.system]
items = [
    "alacritty",
    "libnotify",
    "notification-daemon",
    "networkmanager",
    "network-manager-applet",
    "bluez",
    "bluez-utils",
    "blueman",
    "lxsession",
    "brightnessctl",
    "light",
    "yad",
    "sox",
    "xdg-desktop-portal",
    "xdg-desktop-portal-gtk",
    "xdg-utils",
    "flatpak-xdg-utils",
    "oglo-hyprland-rice-theme-translate-rs",
]
