#!/usr/bin/env bash

log_fatal () {
    rebos api echo fatal "$1"
}

log_info () {
    rebos api echo info "$1"
}

log_warning () {
    rebos api echo warning "$1"
}

die () {
    log_fatal "$1"
    exit 1
}

attxtf_root () {
    sudo bash -c "cat '$1' | grep '$2' || echo '$2' >> '$1'" || return 1
}

sysctl_boot () {
    attxtf_root "/etc/sysctl.d/99-sysctl.conf" "$1" || return 1
}

sudo cp ~/.config/rebos/environment /etc/environment
sudo cp ~/.config/rebos/sddm.conf /etc/sddm.conf

if [[ -f /usr/bin/helix ]]; then
	command -v hx > /dev/null 2>&1 || sudo ln -s /usr/bin/helix /usr/local/bin/hx
fi

if pacman -Qs firewalld > /dev/null 2>&1; then
  sudo systemctl disable firewalld --now
  sudo pacman -Rns firewalld
  sudo pacman -S ufw
  sudo systemctl enable ufw --now
fi

if pacman -Qs virt-manager > /dev/null 2>&1; then
  sudo usermod -aG libvirt $USER
  sudo usermod -aG kvm $USER
  sudo usermod -aG video $USER
  
  sudo systemctl enable libvirtd.service --now

  sudo virsh net-autostart default > /dev/null
fi

if pacman -Qs auto-cpufreq > /dev/null 2>&1; then
  sudo systemctl enable auto-cpufreq --now
fi

if [[ "$(cat /proc/sys/kernel/sysrq)" == "1" ]]; then
    log_info "SysRQ already enabled..."
else
    log_info "Enabling SysRQ..."
    sysctl_boot "kernel.sysrq = 1" || die "Failed to enable SysRQ! (For Every Boot)"
    sudo sysctl kernel.sysrq=1 > /dev/null || log_warning "Failed to start SysRQ! (For Just This Session)"
fi
