[managers.system]
items = [
  "cliphist",
  "waybar",
  "rofi-lbonn-wayland-git",
  "swww",
  "swaync",
  "nwg-look",
  "eww-wayland",
  "qt5-wayland",
  "gammastep",
  "grim",
  "slurp",
  "wlr-randr",
]
