# --------------------- #
#    Generation File    #
# --------------------- #

imports = [
    "intensive",
    "intensive_proprietary",
]

pkgs = [
    "xf86-video-amdgpu",
    "vulkan-radeon",
    "lib32-vulkan-radeon",
]

flatpaks = [
    "net.ankiweb.Anki",
]

crates = [
]
