# --------------------- #
#    Generation File    #
# --------------------- #

imports = [
    "intensive",
    "intensive_proprietary",
    "gpu_drivers/amd",
    "laptop",
]

pkg_managers.system.pkgs = [
]

pkg_managers.flatpak.pkgs = [
    "net.ankiweb.Anki",
]
