# --------------------- #
#    Generation File    #
# --------------------- #

imports = [
    "intensive",
    "intensive_proprietary",
    "gpu_drivers/amd",
]

pkgs = [
]

flatpaks = [
    "net.ankiweb.Anki",
]

crates = [
]
