imports = [
  "xdg",
]

[managers.system]
items = [
  "coreutils",
  "binutils",
  "util-linux",
  "dbus",
  "seatd",
  "elogind",
  "polkit",
  "ntp",
  "mesa-dri",
  "gcc",
  "make",
  "cmake",
  "meson",
  "curl",
  "wget",
  "zip",
  "unzip",
  "git",
  "bash-completion",
  "gettext",
  "vim",
  "tar",
  "xmirror",
]

[managers.runit]
items = [
  "dbus",
  "seatd",
  "polkitd",
  "ntpd",
]
