imports = [
  "kde_full",
  "laptop",
  "hack",
]

[managers.system]
items = [
  "www-client/librewolf-bin",
  "www-client/brave-browser",
  "dev-lang/rust-bin",
  "app-office/libreoffice-bin",
  "net-misc/rustdesk-bin",
]

[managers.flatpak]
items = [
]

[managers.cargo]
items = [
]
