# --------------------- #
#    Generation File    #
# --------------------- #

imports = [
  "initial_packages",
  "core_packages",
  "programming_languages",
  "hyprland",
  "proprietary",
  "sddm_themes",
]

[managers.serv_startup]
items = [
  "sddm",
]

[managers.system]
items = [
  "meson",
  "ninja",
  "flatpak",
  "gparted",
  "helix",
  "neovim",
  "nodejs",
  "bat",
  "eza",
  "brave-bin",
  "thunar",
  "noto-fonts-emoji",
  "qt5ct",
  "pipewire",
  "sddm-git",
  "neo-matrix-git",
  "cmatrix-xterm-256color",
  "clido",
  "tuido",
  "flattools",
  "dmenu-to-rofi",
  "cermic",
  "grape",
  "pytool",
  "rupell",
  "zellij",
  "fastfetch",
  "cutefetch",
  "uwufetch",
  "retch",
  "pfetch-rs-bin",
  "chafa",
  "starship",
  "namcap",
  "cava",
  "gimp",
  "inkscape",
  "zsh",
  "nushell",
  "gthumb",
  "lite-xl",
  "mpv",
  "rhythmbox",
  "gnome-calculator",
  "binum",
  "coin-flipper",
  "appimagelauncher",
  "ncdu",
  "libreoffice-fresh",
  "wine",
  "transmission-gtk",
  "htop",
  "btop",
  "nvtop",
  "tty-clock-git",
  "asciiquarium",
  "lolcat",
  "catlol",
  "lavat-git",
  "arp-scan",
  "tigervnc",
  "dir-watcher",
  "gnome-disk-utility",
  "arg-info",
  "calibre",
  "netget-cli",
  "gnu-netcat",
  "lazygit",
  "browsh-bin",
  "sex",
  "fortune-mod",
  "festival",
  "festival-us",
  "cowsay",
  "tayum-cli",
  "kooha",
  "gnome-mines",
  "pipes.sh",
  "pipes-rs",
  "bettercap",
  "rainfuck-cli",
  "pmbootstrap",
  "bullshit",
  "yazi",
  "ghex",
  "senpai",
  "shabi",
  "oglo-cpu-asm",
  "warpinator",
]

[managers.flatpak]
items = [
  "com.github.tchx84.Flatseal",
  "org.gabmus.whatip",
  "net.supertuxkart.SuperTuxKart",
  "org.signal.Signal",
  "org.supertuxproject.SuperTux",
  "org.gnome.World.PikaBackup",
  "org.raspberrypi.rpi-imager",
  "com.github.reds.LogisimEvolution",
  "xyz.armcord.ArmCord",
  "com.obsproject.Studio",
  "org.godotengine.Godot",
  "org.xonotic.Xonotic",
  "com.stremio.Stremio",
  "org.kde.krita",
]

[managers.cargo]
items = [
  "bacon",
  "cargo-info",
  "cargo-update",
  "cargo-expand",
  "cargo-show-asm",
  "irust",
  "speedtest-rs",
  "wiki-tui",
  "mprocs",
  "uwuify",
]
