# ----------------------------------- #
#    Package Manager Configuration    #
# ----------------------------------- #

add = "paru -S #:?"
remove = "paru -Rns #:?"
sync = "paru -Syy"
upgrade = "paru -Syyu"

# ------------------------------- #
#    Additional configuration.    #
# ------------------------------- #

plural_name = "system packages"

hook_name = "system_packages"

[config]
many_args = true
