imports = [
    "virtualbox",
    "virt-manager",
]

[managers.system]
items = [
    "element-desktop",
    "godot",
    "mission-center",
    "blender",
    "waydroid",
    "lutris",
]

[managers.flatpak]
items = [
    "simple64",
    "blanket",
    "blockbench",
    "codium",
    "org.prismlauncher.PrismLauncher",
    "org.kde.kdenlive",
]
