imports = [
    "virtualbox",
    "virt-manager",
]

pkg_managers.system.pkgs = [
    "element-desktop",
    "godot",
    "mission-center",
    "blender",
    "waydroid",
    "lutris",
]

pkg_managers.flatpak.pkgs = [
    "simple64",
    "blanket",
    "blockbench",
    "codium",
    "org.prismlauncher.PrismLauncher",
    "org.kde.kdenlive",
]
