imports = [
    "virtualization",
]

pkgs = [
    "element-desktop",
    "godot",
    "mission-center",
    "blender",
    "waydroid",
    "lutris",
]

flatpaks = [
    "simple64",
    "blanket",
    "blockbench",
    "codium",
    "org.prismlauncher.PrismLauncher",
    "org.kde.kdenlive",
]

crates = [
]
