pkg_managers.system.pkgs = [
  "alacritty",
  "libnotify",
  "notification-daemon",
  "networkmanager",
  "network-manager-applet",
  "bluez",
  "bluez-utils",
  "blueman",
  "papirus-icon-theme",
  "lxsession",
  "brightnessctl",
  "light",
  "yad",
  "sox",
  "mint-themes",
  "xcursor-simp1e-gruvbox-light",
  "xdg-desktop-portal",
  "xdg-desktop-portal-gtk",
  "xdg-utils",
  "flatpak-xdg-utils",
  "oglo-hyprland-rice-theme-translate-rs",
]
